services:
  mysql:
    build:
      ./mysql-database
    ports:
      - 3306:3306
  user:
    build:
      ./stampmarket-user
    ports:
      - 9001:9001

  stamp:
    build:
      ./stampmarket-stamp
    ports:
      - 9002:9002
